[package]
name = "dgt_harvest_rust"
version = "0.1.0"
edition = "2021"

[lib]
name = "dgt_harvest_rust"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.19"
features = ["extension-module"]

[dependencies]
image = "0.24"
rayon = "1.8"
